### ISSUE TITLE
Contribute camel-pi4j component

### ISSUE THREAD

**Issue by hekonsek** [camel-labs/camel-labs#1]

**Comment by gautric** [comment]
Got an camel-raspberrypi component here https://github.com/gautric/camel/tree/master/components/camel-raspberrypi
I also an camel-device-io component ready but it isn't full ready yet

**Comment by davsclaus** [comment]
Whoa sounds good. Also your excellent blog, we should remember to add that as part of the docs, or refer to it from the website.

**Comment by gautric** [comment]
If you want I can push my work asap

**Comment by hekonsek** [comment]
I've created new issue (#3) for the camel-device-io component.

I will also talk to Geert Schuring - he worked on camel-serial and camel-thinkerforge components.

**Comment by hekonsek** [comment]
@gautric I will create a basic structure for the project and ping you. Then you could contribute the RPi component. This is awesome stuff! :)

**Comment by gautric** [comment]
what about the license ? GPL/ASF/EPL ?
your choice will be mine ;-)

**Comment by davsclaus** [comment]
I suggest ASL2 which is also used by many other oss projects. And other projects that some of us work on such as fabric8 hawtio forge, and more and more jboss projects pickup asl over gpl etc.

**Comment by hekonsek** [comment]
Yeah, ASL2 FTW!

**Comment by hekonsek** [comment]
Here [1] is the Maven module for the IoT related components. Feel free to add RPi component there!

[1] https://github.com/camel-labs/camel-labs/tree/master/iot/components

**Comment by hekonsek** [comment]
Hi Greg. I see that you started to contribute the component to the project. Please let us know, when it is ready. Thanks!

**Comment by hekonsek** [comment]
I have fixed parent and groupId of the component. I have also imported Camel BOM (2.15.1) into our BOM.

**Comment by gautric** [comment]
pi4j project releases 1.0 version (http://pi4j.com/#News__Announcements) but pom and jar aren't yet available at Maven central.

**Comment by gautric** [comment]
pi4j project changes to LGPLv3 License

**Comment by gautric** [comment]
GPIO should works fine for Digital, Analog and PWN
IRRπ (in real raspberry π), I just tested it with Digital Input and Output

**Comment by hekonsek** [comment]
@gautric Can you add the component documentation here [1]?

[1] https://github.com/camel-labs/camel-labs/tree/master/iot#camel-raspberry-pi-component

**Comment by hekonsek** [comment]
Is there any additional work related to this component? Any chance to get the docs for the component? I can help with the documentation if needed :) .

**Comment by gautric** [comment]
@hekonsek I am working on ;-)

**Comment by hekonsek** [comment]
Oh cool, just can't wait to brag about the cool stuff we got :) .

**Comment by hekonsek** [comment]
Can we close this one in 0.0.0 release?

**Comment by hekonsek** [comment]
@gautric Can I close this one? Is the basic version of the component and docs ready?

**Comment by gautric** [comment]
impl gpio ok, doc ok,
impl i2c ok, doc ok
we can close it for basic version

**Comment by hekonsek** [comment]
Great! Thanks Greg! You can always add new stuff in the coming version (and I hope you will ;) ).
