### ISSUE TITLE
Build logs series of warning messages when downloading codehaus artifacts

### ISSUE THREAD

**Issue by geertschuring** [camel-labs/camel-labs#111]
the build tries to download from the codehaus repo which has shut down.
[WARNING] Could not transfer metadata org.codehaus.groovy:groovy-eclipse-batch/maven-metadata.xml from/to codehaus.org (http://repository.codehaus.org): Failed to transfer file: http://repository.codehaus.org/org/codehaus/groovy/groovy-eclipse-batch/maven-metadata.xml. Return code is: 410 , ReasonPhrase:Gone.
This does not fail the build luckily, but does look weird.

**Comment by hekonsek** [comment]
Done.
