### ISSUE TITLE
Consider Vert.x as the application framework for the cloudlets

### ISSUE THREAD

**Issue by hekonsek** [camel-labs/camel-labs#112]
Vert.x scales like hell. Much better than anything else really. We should consider using Vert.x as a base for the Cloudlets (instead of Spring Boot) as we might expect extremely heavy load generated by the devices.

**Comment by hekonsek** [comment]
I'm working on the Leshan-based LWM2M device management cloudlet. I will use vert.x there for a try.

**Comment by hekonsek** [comment]
This [1] feature might be awesome for the Vert.x deployed into the gateway! Dynamically loads verticles from the Maven repositories. 

[1] https://github.com/vert-x3/vertx-maven-service-factory/blob/master/README.md

**Comment by jkirklan** [comment]
Are there any downsides to using Vert.x vs. Node or somethings else?

**Comment by hekonsek** [comment]
Actually vert.x is the best option as the underlying technology, as it manages the threads pool the most efficiently. This is big advantage for the resource-constrained devices like gateways.

**Comment by hekonsek** [comment]
I started to develop the Leshan-based device cloudlet using Vert.x.
