### ISSUE TITLE
Prepare Maven release plugin

### ISSUE THREAD

**Issue by hekonsek** [camel-labs/camel-labs#2]
So we could released project to the Maven Central.

**Comment by gautric** [comment]
the cook book : http://central.sonatype.org/pages/ossrh-guide.html

**Comment by hekonsek** [comment]
Yeah, I can handle this one :) .

**Comment by hekonsek** [comment]
I have requested [1] account from Sonatype.

[1] https://issues.sonatype.org/browse/OSSRH-15077

**Comment by hekonsek** [comment]
OSSRH-15077 has been resolved. I should be able to deploy to Maven Central. I will cut a release as soon as we are done with the Raspberry Pi component (#1).

**Comment by geertschuring** [comment]
I'd like to add the tinkerforge component for the 0.0.0 release if that's ok with you. I already started and will push it tonight.

**Comment by hekonsek** [comment]
Sure! No rush from my side. It would be great to have both components included in the release.
