### ISSUE TITLE
Contribute camel-tinkerforge component

### ISSUE THREAD

**Issue by geertschuring** [camel-labs/camel-labs#20]
Code is currently located here: https://bitbucket.org/geertschuring/camel-tinkerforge
I need to check whether packaging the tinkerforge classes inside the component is allowed by the tinkerforge license. If not, I will remove it before migrating the code here.

**Comment by hekonsek** [comment]
Thanks for creating the issue Geert. I have added you the project committers team.

**Comment by geertschuring** [comment]
Thanks. I can't assign issues to my name yet though.

**Comment by davsclaus** [comment]
@geertschuring I think you need to accept the invite then you ought to be able to do so. I can see in github there is a pending invitation to you.

**Comment by geertschuring** [comment]
Thanks @davsclaus, that solved it.

**Comment by hekonsek** [comment]
@geertschuring I'm still not sure when I'm gonna have the time for a Skype call. Maybe you can try to describe the merge problem here in the meantime? Maybe I could help via GitHub comments?

**Comment by geertschuring** [comment]
I'll just move the code over here and file issues. We can solve those later.

**Comment by hekonsek** [comment]
Geert, can you contribute the documentation to the component? Here [1] is our documentation page.

[1] https://github.com/camel-labs/camel-labs/tree/master/iot#camel-tinkerforge-component

**Comment by geertschuring** [comment]
Ah yes, good point. I bet @davsclaus has an idea about generating documentation from the source.

**Comment by hekonsek** [comment]
@davsclaus Geert made a good point. Can we somehow use the new documentation feature of Camel to generate the documentation that we could paste to the GitHub documentation page?

**Comment by hekonsek** [comment]
@davsclaus Is Camel Maven API Component documented somewhere? I can't find it.

**Comment by davsclaus** [comment]
Its a matter of having those annotations in the endpoint class, and then UriPath / UriParam for each option.

https://github.com/camel-labs/camel-labs/blob/master/iot/components/camel-device-io/src/main/java/com/github/camellabs/component/deviceio/gpio/GPIOEndpoint.java#L45

camel-labs has been setup to generate the documentation. The docs is embedded in the JAR as html and json.

To generate a .md or website then we do not have that yet. But the idea is that we will get to that point at Apache Camel so we can maintain the docs more easily, and eventually also get rid of wiki and use proper documentation.

For camel-labs I think its fine to use readme.md files or the likes for docs.

For generating a website for camel-labs

**Comment by hekonsek** [comment]
Until #47 is resolved, let's maintain the documentation manually. @geertschuring Can you add the documentation for the Tinkerforge component? I'd like to start to brag/post/tweet about this component, but we need a reference documentation in place before we do it :) .

**Comment by geertschuring** [comment]
I don't have much documentation for the tinkerforge component yet, and I'm about to go on vacation for two weeks tomorrow. I'll try to document at least a couple of the supported bricklets before I leave so you can start bragging :+1: :smile:

**Comment by hekonsek** [comment]
You can paste a raw draft of the documentation here. I can edit it, add extra descriptions and stuff like that. I just need bare content :) .

**Comment by hekonsek** [comment]
Hi Geert,

I didn't have a chance to work on the Tinkerforge documentation yet. Can you consider adding it now? I'd like to close 0.0.0 release.

**Comment by geertschuring** [comment]
I'll look at it tonight.

**Comment by hekonsek** [comment]
I will appreciate it, thanks!

**Comment by geertschuring** [comment]
I've been reworking the tinkerforge URI syntax which requires a little bit more time. I'll keep you posted. What timeline do you have in mind for 0.0.0 release?

**Comment by davsclaus** [comment]
Should it not be 0.1.0 release, or lest have one digit that is not zero ;)

**Comment by hekonsek** [comment]
Nothing really urgent, but I'd like to cut the release in the coming days. :)

Claus - you are right, let's make it 0.1.0 :)

**Comment by hekonsek** [comment]
Geert, let me know if I can somehow help you in finishing this one.

**Comment by geertschuring** [comment]
Hey, I'm working on it right now. The component is ready for the 0.1 release. I'm working on an installation tutorial with Karaf 4.0.0.M2 since we're on the bleeding edge and stuff :smile:

**Comment by geertschuring** [comment]
Ok, no Karaf 4, camel has no feature files to Karaf 4 yet. Camel 2.15.2 supports Karaf 2.4.2 so I went with that: https://geertschuring.wordpress.com/2015/05/25/running-camel-tinkerforge-on-karaf/

**Comment by hekonsek** [comment]
Thanks Geert!

**Comment by geertschuring** [comment]
@hekonsek I don't seem to have the rights to close this issue. Can you close it for me?

**Comment by hekonsek** [comment]
Yay. Closing then :) .
