### ISSUE TITLE
Add to build instructions that java 8 is required

### ISSUE THREAD

**Issue by davsclaus** [camel-labs/camel-labs#22]
What is the runtime is Java8 also required? Or can it run on the older java 7?

This was the pi component that had a failed build when I tried with java 7

**Comment by hekonsek** [comment]
The question here is what we would assume as a minimal JRE for the project. We can try Java8 - this is new stuff anyway. Any Raspberry Pi comes with Java 8 on Rasbpian out of the box.

What do you think?

**Comment by geertschuring** [comment]
Considering that Oracle ends its security updates for Java 7 this month [1], I'd say we go with Java 8.

[1] https://www.java.com/en/download/faq/java_7.xml

**Comment by davsclaus** [comment]
yeah sure fine with me being java8+

**Comment by davsclaus** [comment]
I guess we can use maven enforcer to require Java8 or higher ?

**Comment by geertschuring** [comment]
The enforcer plugin only forces the use of Java8 at build time, while our Java8 requirement is about runtime if I'm correct.

**Comment by hekonsek** [comment]
Yeah, but you can't enforce runtime usage. JRE will just throw the class loading error if Java < 8 is used. I have added the information about Java 8 requirement to the main page.

**Comment by geertschuring** [comment]
Just like you can't compile for java8 using anything other then JKD8... so what's the point of the enforcing plugin in this case? :)

**Comment by hekonsek** [comment]
- the build fails early. This is important for the bigger projects :) .
- nicer error messages :)

**Comment by geertschuring** [comment]
You're right, the nice and early error message is better then letting the compiler plugin discover that it can't compile the source files.
