### ISSUE TITLE
RaspberryPiComponent - Define as 2 components

### ISSUE THREAD

**Issue by davsclaus** [camel-labs/camel-labs#23]
The 2 endpoints

- I2CEndpoint
- GPIOEndpoint

Dont share anything really and its better to define this as 2 individual components with each of their own scheme, eg

- raspberrypi-pin
- raspberrypi-i2c

Then as separate schemes this works better for Camel and tooling and whatnot.

**Comment by geertschuring** [comment]
On the other hand, the uri scheme might look like this if you keep them as 1 component:
```
from("raspberrypi:i2c?deviceId=wqerty"
.to("log:default");
```

and 

```
from("raspberrypi:gpio?pin=4"
.to("log:default");
```


I have 1 tinkerforge component that supports 16 types of quite different bricklets this way:

```
from("tinkerforge:temperature?uid=T1")
.to("log:output?showHeaders=true");

from("timer:default?period=2000")
.setHeader("duration", constant("1000"))
.setBody(constant("on"))
.to("tinkerforge:dualrelay?uid=dr1");
```

**Comment by gautric** [comment]
Currently camel-raspberry component supports
"raspberrypi://gpio/<gpioId>"  --> raspberrypi://gpio/1
"raspberrypi://i2c/<busId>/<deviceId>" --> raspberrypi://i2c/1/43

**Comment by gautric** [comment]
pi4j doesn't split i2c, spi and gpio into separate libs

**Comment by gautric** [comment]
@geertschuring IMHO for retrieving a resource I prefer use absolute URI (urn://resource/subId/id) than using query string (uri?id=12), because query string is optional, not the absolute URI.

**Comment by geertschuring** [comment]
@gautric Yeah I was thinking the same when I saw your comment. I'll consider refactoring the tinkerforge URI. Although the endoint has default values, and so the uri parameters are really optional.

@davsclaus Maybe the added confusion over 2 different raspberry pi components (while functionally  similar) doesn't justify the neat separation of two technically unrelated code bases.

**Comment by hekonsek** [comment]
If both GPIO and I2C are handled via pi4j library, then I would keep them in the same component.

**Comment by hekonsek** [comment]
On the other hand, Claus is right. From the tooling perspective - two components are better. For example you can assign different icons to them and then display them in the Hawt.io. And tooling is the important stuff :) .

+1 for splitting then.

**Comment by gautric** [comment]
can we provide two components into the same maven artifact ?

**Comment by davsclaus** [comment]
Yeah I was maybe not to detailed. Yes its really about having different scheme names so there is no clash.

But you can have the same component class if you want. Or have a base class and then two extended.

For example we have in camel-ftp 3 components, ftp, ftps and sftp. The first 2 are from the same component. All in same JAR.

**Comment by davsclaus** [comment]
If we know today what we know then if Camel was created then I think we would have enforced a 1:1 between component / endpoint.

**Comment by gautric** [comment]
+1 to split component into one artifact
two schemes will be 
```
"raspberrypi-gpio://<gpioId>"  --> raspberrypi-gpio://1
"raspberrypi-i2c://<busId>/<deviceId>" --> raspberrypi-i2c://1/43
```

any objection ?

**Comment by davsclaus** [comment]
@geertschuring yeah for your 16 tinkerforge then I guess its always a how to slice and dice it question.

Lets say those 16 are different functionalities (I can only guess)

- control led
- measure temperature
- beep
- capture sound
- capture video
- ...

It may still be a good idea to have 16 different schemes as then they are better separated. You can then at both design time with tooling and at runtime get better details, as you can then know that you are using the control led and capture sound schemes which can then have their own little description and documentation.

What is missing is maybe a way to tie all those 16 into the same family = tinkerforge. You can kinda infer this today, if they have same component class etc. But maybe an explicit configuration you set when creating the component. So from a tooling you may add tinkerforge, and then when you want to use it it has 16 different endpoints inside you can choose among.

And then we are not so far from having a Camel "component app store" where components can advertise what they do and what options they have with documentation embedded. But that is another story.

**Comment by gautric** [comment]
DONE

**Comment by hekonsek** [comment]
The new component description API provides labels, right? We might use them to group thinkerforge or rpi stuff together.

**Comment by davsclaus** [comment]
Yes and you can have multiple labels separated by comma. Usually by higher level first eg
```
label="iot,tinkerforge"
```
