### ISSUE TITLE
Should we use "#<issueId> Bla bla"  for commit comment ?

### ISSUE THREAD

**Issue by gautric** [camel-labs/camel-labs#25]

**Comment by davsclaus** [comment]
I think using `#NNN - bla bla` is fine. 

IMHO dont have to many rules and restrictions. It should be easy and fun to work on a project in your spare time ;)

**Comment by hekonsek** [comment]
Yeah, +1 for #ID at the beginning of the comment. But nothing really formal - I would consider it more like a good practice to make the others life easier than some formal rule.
