### ISSUE TITLE
Create camel-iot-utils module

### ISSUE THREAD

**Issue by hekonsek** [camel-labs/camel-labs#28]
Camel IoT modules are supposed to be deployed into two targets:

- field devices (Raspberry Pi, etc.)
- as Cloudlets (#26) into the data center (i.e. Camel Spring Boot fat jars deployed into Fabric8 /Openshift3 for example)

I assume we don't care about the OSGi.

I propose to create the common util module that would:

- include SLF4J API, Guava, Apache Commons, Joda Time (to avoid reinventing the wheel)
- include our custom helpers/utils
- serve as a common utils base used by the Camel IoT Labs modules

**Comment by geertschuring** [comment]
I'm not sure what you mean with modules. Are those same as the components?

**Comment by hekonsek** [comment]
By modules I mean Maven modules :)

**Comment by jkirklan** [comment]
A lot of the IoT work in eclipse is OSGi compliant.   Is this just a fad?

**Comment by geertschuring** [comment]
Yeah the OSGi assumption surprised me too. :) My demo's are OSGi based so I would prefer proper OSGi headers in the manifest.

**Comment by hekonsek** [comment]
After the moment of consideration, I must agree with you. We should support OSGi at least for Kura deployments. Some folks would like to run Karaf on the devices as well.

Forget my comment about OSGi. We should support it. It's just my inner OSGi-hater speaking... ;)

**Comment by geertschuring** [comment]
Hehe, I bet you'd like to give OSGi the spring-boot. :)

**Comment by hekonsek** [comment]
Done.
