### ISSUE TITLE
Add WiFi access points detector to camel-kura

### ISSUE THREAD

**Issue by hekonsek** [camel-labs/camel-labs#29]
I'd like to have an Kura-based endpoint that can scan Wifi networks available near the device:

    from("kura-wifi://SSID").filter(body().isNotNul()).
      to("controlbus:route?routeId=syncCachedData&action=start");

That would be useful for the cases when field device like RaspberryPi caches some data until the WiFi network becomes available. Then, when given SSID is available, Camel route dedicated for data synchronization should be started, so the data cached in the local store are sent to the cloud.

**Comment by hekonsek** [comment]
@davsclaus Can I just move camel-kura from ASF Camel to Camel Labs? I would prefer to maintain camel-kura here, especially that I need to integrate with the Kura artifacts outside the Maven Central. What do you think?

**Comment by davsclaus** [comment]
It would certainly be easier if it hasn't been released from ASF yet. But I can see its in 2.15 release.
You can for sure fork it, and maintain it here.

**Comment by hekonsek** [comment]
I will keep Kura OSGi base module in ASF then, but add new Kura-based features like WiFi component to the Camel Labs. Thanks!

**Comment by hekonsek** [comment]
Done.
