### ISSUE TITLE
Configure Bnd plugin to create correct OSGi headers in the manifests

### ISSUE THREAD

**Issue by geertschuring** [camel-labs/camel-labs#39]
The current build does not run the bnd plugin, leaving the build artifacts with no OSGi headers in the manifest.

**Comment by geertschuring** [comment]
@hekonsek The configuration for the maven-jar-plugin seems to conflict with the Bnd plugin. I think it would be a good idea to keep the camel components build config as much like the "real" camel components as possible. That means moving the config to make the components self executable out, and the config for OSGi compatibility in.

WDYT?

**Comment by davsclaus** [comment]
@geertschuring yeah I think over the years from Apache Camel we have learned that the bnd tools and felix bundle plugin need a bit help from time to time, so having flexibility to tweak the plugin as we can do in the pom.xml at Apache Camel is likely needed.

Also we need for osgi to declare the export service and so on. 

I would suggest to adopt the Camel way of making the components OSGi bundles. 
Usually that is not so invasive as for most components its a few lines of properties in the top.

**Comment by hekonsek** [comment]
@gautric Can we remove these `maven-jar-plugin` entries from the components? I propose to create a dedicated "main runner" fat jars if you need them.

**Comment by geertschuring** [comment]
I have a commit on my laptop that removes the maven-jar-plugin config and adds the correct maven-bundle-plugin config. As soon as @gautric aggrees with this change, I will push it.

**Comment by gautric** [comment]
@hekonsek  @geertschuring  ok to remove
