### ISSUE TITLE
Make upstream Tinkerforge java bindings OSGi compatible

### ISSUE THREAD

**Issue by geertschuring** [camel-labs/camel-labs#41]
Get in touch with the Tinkerforge guys and inform them how to add OSGi headers to their jars so we don't have to wrap the library.

**Comment by geertschuring** [comment]
Created pull request for Tinkerforge.
https://github.com/Tinkerforge/generators/pull/40

**Comment by geertschuring** [comment]
My pull request has been merged by Tinkerforge. The next release of the Tinkerforge java bindings will be OSGi ready.

**Comment by hekonsek** [comment]
Great job! I think we can close this one.
