### ISSUE TITLE
Define versioning strategy

### ISSUE THREAD

**Issue by geertschuring** [camel-labs/camel-labs#43]
We need to decide how to version our releases.

One way would be to follow the camel version which we build against. That means our first release would be 2.15.1. Otherwise it might get confusing to keep track of which version of camel-labs goes with which version of Camel.

**Comment by gautric** [comment]
+1

**Comment by hekonsek** [comment]
Actually we (me and Claus) would like to be free to the ASF lifecycle limitations. For example to release often and don't wait for the Camel releases.

I just prefer using the latest and the greatest Camel, just as we do in Fabric8 for example. Which BTW is released often and what is really cool.

For now I would start with released versioned like 0.0.1, 0.0.2, 0.0.3. Then switch to 0.1.0 when we decide that project is mature enough. This is the Fabric8 approach [1]. We can release whenever we can, almost on daily basis. This is really cool, as we can bring the value to the users really quickly.

[1] https://github.com/fabric8io/fabric8/releases

**Comment by hekonsek** [comment]
@davsclaus Can tell you more about the reasons why slow ASF releases suck :) .

**Comment by davsclaus** [comment]
I also think we should use our own version numbering.

We can then have a page with a matrix showing which versions is compatible with which Camel versions.

For example as the Camel Karaf page
http://camel.apache.org/karaf

And yeah release often is great. Love how hawtio, fabric8 is doing that. And other projects do that too such as Netty. They did 28 releases in 2014.

**Comment by gautric** [comment]
to close ?

**Comment by hekonsek** [comment]
Closing - let's stay with the independent Fabric8-like versioning.
