### ISSUE TITLE
Group plugin and dependency configuration in 1 pom file

### ISSUE THREAD

**Issue by geertschuring** [camel-labs/camel-labs#48]
We've currently got multiple places where plugins and profiles are configured:

* https://github.com/camel-labs/camel-labs/blob/master/pom.xml
* https://github.com/camel-labs/camel-labs/blob/master/bom/pom.xml
* https://github.com/camel-labs/camel-labs/blob/master/iot/components/pom.xml

I would like to suggest to:

* use the BOM (Bill Of Materials) only for DependencyManagement like the maven docs for the import scope suggests [1], and move the plugin and profile config to the project parent pom.

*or*
* remove the separate bom and merge its content with the project parent pom (like Camel)

@hekonsek @davsclaus @gautric @jkirklan 
What do you think?

[1] https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

**Comment by hekonsek** [comment]
The second option seems fine for me. I.e. using the Camel approach. We can just keep the name `bom`, instead of `parent`, as the former is more friendly for the users importing that module as Bill Of Materials.

**Comment by hekonsek** [comment]
I've changed the structure of the project, to follow the ASF Camel one. Now we need to move some things from BOM to root POM, but we can do it with in the next release. This is may be finished in the next release.
