### ISSUE TITLE
Create camel-pubnub component

### ISSUE THREAD

**Issue by hekonsek** [camel-labs/camel-labs#62]
@pax95 offered to contribute that component - https://github.com/pax95/camel-pubnub .

**Comment by pax95** [comment]
I'll make some room for the coming week to make something working. Stay tuned.

**Comment by hekonsek** [comment]
+1

**Comment by davsclaus** [comment]
Good to hear @pax95 you are still riding the Camel ;)

**Comment by pax95** [comment]
@davsclaus Once a Camel rider always a Camel rider ;)

@hekonsek Made some changes at my repo. 
Currently I don't have any IoT device. If you have a raspberry (and got the time) could you try out how the Camel/pubnub combo works there ? You can use my pub/sub keys if you want.

I'll add some unittests for the current implementation next week or so. 
Currently only multicast is implemented. 

Unicast (master to device(s) or maybe even device to device) needs some digging/thinking, since devices might want to announce on which channel they are listening for private messages.

**Comment by hekonsek** [comment]
Hi Preben. I've just added you to the committers group. Would you be so kind and add the component to the project? I will try to give it a try on my Raspberry soon.

**Comment by hekonsek** [comment]
This PubNub stuff looks really cool. BTW Did you have a chance to use PubNub in the production?

**Comment by pax95** [comment]
Super. I'll begin to move my repo here soon.
Yeah. Pubnub seems cool, and you can have a resilient global messaging platform up and running with a few clicks. 
Up until now I didn't have any use case for PubNub, so I don't really have any stories from the trenches.

**Comment by pax95** [comment]
Component development moved here with commit https://github.com/camel-labs/camel-labs/commit/b509a9eb08fd6ff26c371ea27235c259d899e842
Will continue to fix missing tests, and add features here.

**Comment by hekonsek** [comment]
Great! Thanks Preben!

Would you be so kind and add the documentation [1] to the component as well?

[1] https://github.com/camel-labs/camel-labs/blob/master/iot/readme.md

**Comment by pax95** [comment]
sure. Just tied up in a lot of work currently.

**Comment by hekonsek** [comment]
Take your time. It is not urgent :) .

**Comment by pax95** [comment]
Added documentation and tests for the current features. 

The pubnub library brings in the following dependencies:
    [INFO] +- com.pubnub:pubnub:jar:3.7.2:compile
    [INFO] |  +- org.json:json:jar:20090211:compile
    [INFO] |  \- org.bouncycastle:bcprov-jdk16:jar:1.46:compile

The org.json:json:jar:20090211 is not a osgi bundle. 
What is the best way to handle this regarding eg. feature.xml and osgi stuff ?

**Comment by hekonsek** [comment]
You have to wrap in the the feature file I'm afraid :) You can also register the ticket (ideally pull request) for the `org.json:json` to make this artifact the OSGi bundle.

**Comment by hekonsek** [comment]
Are we done with the first version of the component and the documentation for it? I'd like to announce it as a part of the 0.0.0 release.

**Comment by pax95** [comment]
Yeah - Got some small changes in the pipeline - changing producer to DefaultAsyncProducer and endpoint docs. Will try to commit the last changes tonight :-)

**Comment by hekonsek** [comment]
Great thanks Preben. I also can't wait to play with the pubSub on my RPi!

**Comment by pax95** [comment]
I think the current features covers a first release candidate.
I left out channel multiplexing http://www.pubnub.com/docs/java/javase/overview/stream-controller.html#_pubnub_multiplexing. This might be interesting to implement in a later release.

@hekonsek I would love to hear how it works on a real RPi when you try it out. 
I didn't find the time to dig into what device to buy (any recommendations?) and try it out. it's a device jungle out there. 
Secondary I would like to find a use case to try out - something not a weather station, and a pubnub remote controlled drone might be taking a bit too far.  

I'll close the ticket now if you agree.

**Comment by hekonsek** [comment]
Great! Thanks for the contribution.

Regarding the device - I own Raspberry Pi 2. It is really fast. And also easy to start with. It is just a small computer using SD card instead of the HDD :) .

Cheers!
