### ISSUE TITLE
Release version 0.1.0

### ISSUE THREAD

**Issue by hekonsek** [camel-labs/camel-labs#67]
I would like to cut 0.0.0 release, so my gateway installation script [1] could download the latest gateway fat jar from Maven central.

FYI Gateway is a Spring Boot based fat jar that can be used as a "default" application installed on Rasbian to collect the messages from the sensors and send them to the data center.

[1] https://github.com/camel-labs/camel-labs/blob/master/iot/initd/rasbian/get-camel-labs-iot-gateway-rasbian.sh

**Comment by hekonsek** [comment]
Let's try to focus on closing the task we have assigned to 0.0.0 milestone.

**Comment by geertschuring** [comment]
The Tinkerforge component is ready, so I think we're good for the 0.1 release.

**Comment by hekonsek** [comment]
Great. I will cut the release soon.

**Comment by hekonsek** [comment]
Done.
