### ISSUE TITLE
Create LED hearbeat indicator for gateway

### ISSUE THREAD

**Issue by hekonsek** [camel-labs/camel-labs#74]
This will be a nice addition to the MQTT heartbeats. Flushing the LED at the same time when MQTT message has been sent (i.e. every 5 second).

**Comment by gautric** [comment]
for common message you can use wiretap like this
from("i2c").wiretap("pi4j-gpio://12").to("mqtt://")

**Comment by hekonsek** [comment]
Yeah, I was thinking about something like this. :) BTW Why do you read from i2c here?

**Comment by gautric** [comment]
It was an sample ;-)

**Comment by hekonsek** [comment]
OK, just wanted to be sure :)

**Comment by gautric** [comment]
TODO : add default gpioId into configuration
