### ISSUE TITLE
Add components to Camel Components page

### ISSUE THREAD

**Issue by geertschuring** [camel-labs/camel-labs#84]
The Camel components page has an "external" section. We should add our components there.

http://camel.apache.org/components.html

**Comment by hekonsek** [comment]
+1

**Comment by gautric** [comment]
I've started to include pi4j component but I can't see it on the list https://cwiki.apache.org/confluence/display/CAMEL/pi4j-gpio :-(

**Comment by geertschuring** [comment]
@gautric You need to add it here: https://cwiki.apache.org/confluence/display/CAMEL/Component+List+External

**Comment by gautric** [comment]
"à la main / from scratch " ok, thx

**Comment by davsclaus** [comment]
I think the pubsub is missing. Could anyone add that?
https://github.com/camel-labs/camel-labs/tree/master/iot/components/camel-pubnub

**Comment by hekonsek** [comment]
Just added the PubNub component.

**Comment by pax95** [comment]
@hekonsek Thanks. Missed this thread
